### ISSUE TITLE
SWAN only running with one processor

### ISSUE THREAD

**Issue by rececilio** [jcwarner-usgs/COAWST#189]
Hello.
I have been running ROMS-SWAN experiments in v3.7 with only one node for SWAN without any problem.
However, when I try more than one, it crashes with a "segmentation fault - invalid memory reference". 
The log file stops in the respective node in the "Process Information:" part.
I just changed the coupling.in and the command mpirun -npX, adding one node in both.
Also tried it on a different machine. Same result.
What am I missing here? Are there any more changes to run SWAN in multiple nodes?
Thanks.

****
Error termination. Backtrace:
At line 370 of file waves_coupler.f90
Fortran runtime error: Index '1' of dimension 1 of array 'globalsegmap_g' above upper bound of 0

Error termination. Backtrace:
#3  0x5578cce9ad7e in __waves_coupler_mod_MOD_initialize_wav_routers
	at /home/renato/Desktop/MyCOAWST/Hcast/CTG/Build_romsG/waves_coupler.f90:370
#4  0x5578cce6f794 in __waves_control_mod_MOD_swan_driver_init
	at /home/renato/Desktop/MyCOAWST/Hcast/CTG/Build_romsG/waves_control.f90:84
#5  0x5578c8a92954 in mct_driver
	at /home/renato/Desktop/MyCOAWST/Hcast/CTG/Build_romsG/master.f90:217
#6  0x5578c8a933ec in main
	at /home/renato/Desktop/MyCOAWST/Hcast/CTG/Build_romsG/master.f90:20
#3  0x55eac5baad7e in __waves_coupler_mod_MOD_initialize_wav_routers
	at /home/renato/Desktop/MyCOAWST/Hcast/CTG/Build_romsG/waves_coupler.f90:370
#4  0x55eac5b7f794 in __waves_control_mod_MOD_swan_driver_init
	at /home/renato/Desktop/MyCOAWST/Hcast/CTG/Build_romsG/waves_control.f90:84
#5  0x55eac17a2954 in mct_driver
	at /home/renato/Desktop/MyCOAWST/Hcast/CTG/Build_romsG/master.f90:217
#6  0x55eac17a33ec in main
	at /home/renato/Desktop/MyCOAWST/Hcast/CTG/Build_romsG/master.f90:20

Then several lines with direct and indirect memory leaks and finally:
SUMMARY: AddressSanitizer: 111609 byte(s) leaked in 404 allocation(s).

**Comment by rececilio** [comment]
FOUND IT!

It is not possible to use a single restart file created with one node in a multi-node run, unless using the command INIT HOTSTART SINGLE.
I just started from rest, commenting out the line INIT HOTSTART in swan.in.

Solved and closed.
I am leaving it in here, in case someone else has the same problem.
