### ISSUE TITLE
cowast installation

### ISSUE THREAD

**Issue by jiangdongZ** [jcwarner-usgs/COAWST#196]
When I install MTC
make[1]: Entering directory `/home/jiangdong/Bulid_COAWST/COAWST/Lib/MCT/mpeu'
gcc -c -DFORTRAN_UNDERSCORE_ -DSYSLINUX -DCPRINTEL -O  get_zeits.c
gfortran -c -I/home/jiangdong/Bulid_COAWST/LIBRARIES/mpich/include -DSYSLINUX -DCPRINTEL -O2 -m64  -w -ftz -assume byterecl  m_mpif.F90
gfortran: error: byterecl: No such file or directory
gfortran: error: unrecognized command line option ‘-ftz’
gfortran: error: unrecognized command line option ‘-assume’
make[1]: *** [m_mpif.o] Error 1
make[1]: Leaving directory `/home/jiangdong/Bulid_COAWST/COAWST/Lib/MCT/mpeu'
make: *** [subdirs] Error 2
I have installed three environments in total, once successfully, and twice because of this problem. I want to know how to solve it.

**Comment by jcwarner-usgs** [comment]
well, the issue is that gfortran can not understand those command arguments.
so there is probably a mismatch between the commands and the compiler.
look in the Makefile.conf and see if the compiler flags are correct for the compiler that is listed.
Did  you do the make config?
is that the whole output?

**Comment by jiangdongZ** [comment]
Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
#0  0x2B443989D6D7
#1  0x2B443989DD1E
#2  0x2B443A9E63FF
#0  0x2B621385A6D7
#1  0x2B621385AD1E
#2  0x2B62149A33FF
#3  0x96EAAC in swoexd_
#3  0x96EAAC in swoexd_
#4  0x985D35 in swouta_
#4  0x985D35 in swouta_
#5  0x8CC2E8 in swan_cpl_
#5  0x8CC2E8 in swan_cpl_
#6  0x85AA9D in __waves_control_mod_MOD_swan_driver_run
#6  0x85AA9D in __waves_control_mod_MOD_swan_driver_run
#7  0x40DCDC in MAIN__ at master.f90:?
#7  0x40DCDC in MAIN__ at master.f90:?
I found it is due to the SWAN model."I found that it runs when I provide the SWAN wind field file, but it cannot run when I don't provide it (it stops after running for 30 minutes). In the coupling, shouldn't I leave it blank?"
[scs_swan_cowast.txt](https://github.com/DOI-USGS/COAWST/files/13523752/scs_swan_cowast.txt)
